/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AllowedEmails": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MetaAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MetaAppSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NextauthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NextauthUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "TiktokClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TiktokClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TokenEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitterClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitterClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}