// sst.d.ts - Type stubs for SST v3 Ion globals
// These are normally provided by .sst/platform/config.d.ts (gitignored, generated by `npx sst install`)

declare function $config(config: {
  app(input: { stage?: string }): {
    name: string;
    removal: string;
    protect?: boolean;
    home: string;
    providers?: Record<string, unknown>;
  };
  run(): Promise<void> | void;
}): unknown;

declare function $interpolate(
  strings: TemplateStringsArray,
  ...values: unknown[]
): string;

declare const $app: { stage: string };

declare namespace sst {
  class Secret {
    constructor(name: string);
    value: string;
  }

  namespace aws {
    class Bucket {
      constructor(
        name: string,
        args?: {
          public?: boolean;
          cors?: Array<{
            allowedMethods?: string[];
            allowedOrigins?: string[];
          }>;
          transform?: Record<string, unknown>;
          [key: string]: unknown;
        }
      );
      name: string;
      domain: string;
    }

    class Nextjs {
      constructor(
        name: string,
        args?: {
          link?: unknown[];
          environment?: Record<string, unknown>;
          transform?: Record<string, unknown>;
          [key: string]: unknown;
        }
      );
    }

    class Cron {
      constructor(
        name: string,
        args?: {
          schedule?: string;
          job?: {
            handler?: string;
            environment?: Record<string, unknown>;
            timeout?: string;
            logging?: Record<string, unknown>;
            concurrency?: number;
            [key: string]: unknown;
          };
          [key: string]: unknown;
        }
      );
    }
  }
}
